version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-password}
      POSTGRES_USER: ${DATABASE_USERNAME:-postgres}
      POSTGRES_DB: ${DATABASE_NAME}

  app:
    image: alexmatrosov/devops-for-programmers-project-74
    build:
      context: .
      dockerfile: Dockerfile.production
    ports:
      - 8080:8080
    command: npm test
    environment:
      DATABASE_NAME: "${DATABASE_NAME:-postgres}"
      DATABASE_USERNAME: "${DATABASE_USERNAME:-postgres}"
      DATABASE_PASSWORD: "${DATABASE_PASSWORD:-password}"
      DATABASE_PORT: 5432
      DATABASE_HOST: db
    depends_on:
      - db
