version: '3'
services:
  app:
    image:  mrnion/devops-for-programmers-project-74
    build:
      context: .
      dockerfile: Dockerfile.production
    ports:
      - 8080:8080
    command: npm test
